// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1615:Element return value should be documented", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.ConditionAction.ExecuteAsync(WorkflowEngine.Core.Strategies.StrategyContextData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1615:Element return value should be documented", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.SelectCaseAction.ExecuteAsync(WorkflowEngine.Core.Strategies.StrategyContextData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "<Pending>")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.ConditionAction.ExecuteConditionAsync(WorkflowEngine.Core.Strategies.StrategyContextData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.Parameters.Read(System.Xml.Linq.XElement,WorkflowEngine.IInstance)~WorkflowEngine.Core.Evaluation.Parameters")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.StrategyAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.ContextData.SetValueAsJsonNode(System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.ContextData.SetValueAsJsonNode(System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CustomAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.ConnectorAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.Parameters.Read(System.Xml.Linq.XElement,WorkflowEngine.IInstance)~WorkflowEngine.Core.Evaluation.Parameters")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CounterSetAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CounterSetAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CounterGetAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CounterGetAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Dependencies.Counters.CounterEvaluator.Evaluate~System.Object")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Dependencies.Counters.CounterEvaluator.#ctor(System.Collections.Generic.List{WorkflowEngine.Core.Dependencies.Counters.CounterInfo},System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Actions.Implementations.CounterGetAction.ExecuteAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Dependencies.Counters.CounterEvaluator.Evaluate(System.Collections.Generic.IEnumerable{WorkflowEngine.Core.Dependencies.Counters.CounterData},System.String,System.String,System.String,System.Int32)~System.Object")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:WorkflowEngine.Core.Evaluation.ParameterTypeEnum")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.RandomExtensions.GetRandom(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.RandomExtensions.GetHoursRange(System.String)~System.Double")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.RandomExtensions.GetHoursRange(System.String)~System.Double")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.RandomExtensions.GetHoursRange(System.String)~System.Double")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.RandomExtensions.GetRandom(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.Evaluator.EvaluateXPath(System.Xml.XmlDocument,System.String,System.Boolean)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Evaluation.Evaluator.EvaluateXPath(System.String,System.Boolean)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.ContextData.GetValue(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:WorkflowEngine.Core.Dependencies.Counters.CounterEvaluator.SwapTypes(System.Object)~System.Object")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:WorkflowEngine.Core.Evaluation.XPathExtensions.XPathExtensionFunctions.ArgTypes")]
[assembly: SuppressMessage("Design", "CA1010:Generic interface should also be implemented", Justification = "<Pending>", Scope = "type", Target = "~T:WorkflowEngine.Core.Evaluation.XPathExtensions.CustomXsltContext")]
